---
name: Make Repository

on:
  push:
    branches:
      - main
      - debug
      - feature/**
  schedule:
    - cron: "20 23 * * 0"

jobs:
  pkgbuild:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Makepkg Build and Check
      id: makepkg
      uses: Pinghigh/pkgbuild-action@v5.1
      with:
        makepkgArgs: "--skippgpcheck --noconfirm"

    - name: Print Package Files
      run: |
        echo "Successfully created the following package archive"
        echo "Package: ${{ steps.makepkg.outputs.pkgfile0 }}"
